### ISSUE TITLE
大佬，请问这个怎么用呀？

### ISSUE THREAD

**Issue by LingZhenKai** [Caikun-Peng/MAAHG2#1]
我刚30级可以用吗？

**Comment by Caikun-Peng** [comment]
我还有一些基本的功能没有写完, 尤其是还没有实现全自动战斗, 目前能实现的只有 [README](https://github.com/Caikun-Peng/MAAHG2/blob/main/README.md#目标功能) 里面打勾的功能. 

你可以按照下面的步骤来用(帮我测试):

1. 克隆仓库  
    完整克隆本项目及子项目:  
    ```bash
    git clone --recursive https://github.com/Caikun-Peng/MAAHG2.git
    ```
    **请注意, 一定要完整克隆子项目, 不要漏了 `--recursive`, 也不要下载 zip 包!**
2. 下载 MaaFramework 的 [Release 包](https://github.com/MaaXYZ/MaaFramework/releases), 解压到 `deps` 文件夹中. 
3. 运行安装脚本 `install.py`.
4. 运行 `install/MaaPiCli.exe`.
5. 按照 `MaaPiCli` 显示的步骤进行后续操作.

我不清楚30级能不能快捷战斗虚轴之庭, 别应该都能用? 

如果你是用手机连接电脑的话, 可以试试 [FightStart](https://github.com/Caikun-Peng/MAAHG2/blob/main/assets/resource/mix/exec_agent/FightStart.py) 和 [FightEnd](https://github.com/Caikun-Peng/MAAHG2/blob/main/assets/resource/mix/exec_agent/FightEnd.py) 能不能半自动打关.

**Comment by Caikun-Peng** [comment]
更新了一下, 现在的流程是这样:

1. 克隆仓库  
    完整克隆本项目及子项目:  
    ```bash
    git clone --recursive https://github.com/Caikun-Peng/MAAHG2.git
    ```
    **请注意, 一定要完整克隆子项目, 不要漏了 `--recursive`, 也不要下载 zip 包!**
2. 下载 MaaFramework 的 [Release 包](https://github.com/MaaXYZ/MaaFramework/releases), 解压到 `deps` 文件夹中. 
3. 进入 `src` 文件夹, 运行 `main.py` 脚本.

但是现阶段只支持混服.

**Comment by Caikun-Peng** [comment]
下载最新发布版: [releases](https://github.com/Caikun-Peng/MAAHG2/releases) 并解压

运行解压后的 MAAHG2.exe

现阶段任务`打开游戏`只支持混服
